=== jmjuanes/fonticon/metadata.schema.json
{
    "$id": "https://icons.josemi.xyz/metadata.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Icon metadata schema",
    "description": "A JSON Schema for the metadata object of an icon",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "version": {
            "type": "string"
        },
        "contributors": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "categories": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "uniqueItems": true
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "uniqueItems": true
        }
    }
}

=== jmjuanes/fonticon/metadata/coffee.json
{
    "$schema": "../metadata.schema.json",
    "name": "coffee",
    "version": "0.1.0",
    "contributors": [
        "jmjuanes"
    ],
    "categories": [],
    "tags": [
        "coffee",
        "drink",
        "morning",
        "hot",
        "cup",
        "expresso",
        "latte",
        "cafe",
        "mug"
    ]
}

=== jmjuanes/fonticon/metadata/arrows-split.json
{
    "$schema": "../metadata.schema.json",
    "name": "arrows-split",
    "version": "0.2.0",
    "contributors": [
        "jmjuanes"
    ],
    "categories": [],
    "tags": [
        "arrows",
        "direction",
        "navigation",
        "split",
        "divide",
        "separate"
    ]
}

=== jmjuanes/fonticon/metadata/sd-card.json
{
    "$schema": "../metadata.schema.json",
    "name": "sd-card",
    "version": "0.4.0",
    "contributors": [
        "jmjuanes"
    ],
    "categories": [],
    "tags": [
        "sd",
        "card",
        "data",
        "disk",
        "information",
        "photos",
        "images",
        "media"
    ]
}

=== jmjuanes/fonticon/metadata/chart-area.json
{
    "$schema": "../metadata.schema.json",
    "name": "chart-area",
    "version": "0.1.0",
    "contributors": [
        "jmjuanes"
    ],
    "categories": [],
    "tags": [
        "chart",
        "area",
        "data",
        "diagram",
        "statistics",
        "graph",
        "analysis"
    ]
}

=== jmjuanes/fonticon/metadata/aspect-ratio.json
{
    "$schema": "../metadata.schema.json",
    "name": "aspect-ratio",
    "version": "0.1.0",
    "contributors": [
        "jmjuanes"
    ],
    "categories": [],
    "tags": [
        "aspect",
        "ratio",
        "size",
        "dimensions",
        "screen",
        "width",
        "height"
    ]
}

=== jmjuanes/fonticon/metadata/car-front.json
{
    "$schema": "../metadata.schema.json",
    "name": "car-front",
    "version": "0.4.0",
    "contributors": [
        "jmjuanes"
    ],
    "categories": [],
    "tags": [
        "car",
        "front",
        "vehicle",
        "city",
        "transport",
        "drive",
        "journey",
        "trip"
    ]
}
